import { MidiParser, MidiPlayer } from "./midi.js";

const DEFAULT_SETTINGS = Object.freeze({ masterVolume: 0.5, musicVolume: 0.5, sfxVolume: 0.5 });

/** Browser audio infrastructure consumed through AudioAdapter. */
export class SoundService {
  static _audioCtx = null; static _buffers = new Map(); static _soundMap = {}; static _midiData = new Map(); static _musicPlayer = null; static _sfxCount = 0; static _currentMusicKey = null;
  static _settings = { get: key => DEFAULT_SETTINGS[key] };
  static configureSettings(settings) { if (!settings || typeof settings.get !== 'function') throw new TypeError("SoundService requires a settings query contract."); this._settings = settings; this.updateVolumes(); }
  static _volume(kind) { return Number(this._settings.get('masterVolume') ?? DEFAULT_SETTINGS.masterVolume) * Number(this._settings.get(kind) ?? DEFAULT_SETTINGS[kind]); }
  static async init(soundMap) { this._soundMap = soundMap || {}; this._initializeContext(); return this.loadAll(); }
  static _initializeContext() { if (!this._audioCtx && typeof window !== 'undefined' && (window.AudioContext || window.webkitAudioContext)) this._audioCtx = new (window.AudioContext || window.webkitAudioContext)(); if (this._audioCtx && !this._musicPlayer) this._musicPlayer = new MidiPlayer(this._audioCtx); }
  static async loadAll() { if (!this._audioCtx) return; const promises=Object.entries(this._soundMap).map(([k,v])=>typeof v==='string'?this.loadSound(k,v):Promise.resolve()); const folder='assets/midi/'; let files=['battle1.mid','dungeon1.mid','town1.mid','event1.mid','event2.mid','victory1.mid','coverCapsuleHello.mid','emotional1_bitSad.mid','emotional2_sadNostalgic.mid','emotional3_sadSad.mid','event3.mid','event4_darkJester.mid','event5_nostalgia.mid','event6_happyfinality.mid','event7_happyPrelude.mid','event8_yearning.mid','event9_magical.mid']; try{const response=await fetch(folder);if(response.ok){const text=await response.text(),found=[];for(const match of text.matchAll(/href="([^"]+\.mid)"/g)){const name=decodeURI(match[1]).split('/').pop();if(name&&!found.includes(name))found.push(name);}if(found.length)files=found;}}catch(e){console.warn("Dynamic MIDI scan failed, using fallback list.",e);} files.forEach(file=>promises.push(this.loadMidi(file.replace(/\.mid$/i,''),folder+file))); await Promise.allSettled(promises); }
  static async loadSound(key,path){if(!this._audioCtx)return;try{const response=await fetch(path);if(!response.ok)throw new Error(`HTTP error ${response.status}`);this._buffers.set(key,await this._audioCtx.decodeAudioData(await response.arrayBuffer()));}catch(error){console.warn(`SoundService: Failed to load sound '${key}' from '${path}'.`,error);}}
  static async loadMidi(key,path){if(!this._audioCtx)return;try{const response=await fetch(path);if(!response.ok)throw new Error(`HTTP error ${response.status}`);this._midiData.set(key,new MidiParser(await response.arrayBuffer()).parse());}catch(error){console.warn(`SoundService: Failed to load midi '${key}' from '${path}'.`,error);}}
  static playMusic(key){this._initializeContext();if(!this._audioCtx)return;if(this._audioCtx.state==='suspended')this._audioCtx.resume();if(this._currentMusicKey===key&&this._musicPlayer.isPlaying){this.updateVolumes();return;}const data=this._midiData.get(key);if(!data){console.warn(`SoundService: Music '${key}' not found or not loaded.`);this.stopMusic();return;}this._currentMusicKey=key;this._musicPlayer.load(data);this._musicPlayer.play(true);this.updateVolumes();}
  static stopMusic(){if(this._musicPlayer)this._musicPlayer.stop();this._currentMusicKey=null;} static pauseMusic(){if(this._musicPlayer)this._musicPlayer.pause();} static resumeMusic(){if(this._musicPlayer)this._musicPlayer.resume();} static isMusicPlaying(){return !!(this._musicPlayer&&this._musicPlayer.isPlaying);} static getMusicDuration(){return this._musicPlayer?this._musicPlayer.duration:0;} static getMusicTime(){return this._musicPlayer?this._musicPlayer.currentTime:0;} static getCurrentMusicKey(){return this._currentMusicKey;} static getMusicKeys(){return Array.from(this._midiData.keys()).sort();} static getSfxKeys(){return Object.keys(this._soundMap).sort();}
  static getDebugMidiData(){return this._midiData;} static getDebugSoundMap(){return this._soundMap;}
  static updateVolumes(){if(!this._audioCtx)return;const musicVol=this._volume('musicVolume');if(this._sfxCount>0){if(this._musicPlayer)this._musicPlayer.setVolume(0);}else if(this._musicPlayer)this._musicPlayer.setVolume(musicVol*.6);}
  static async play(key,options={}){const sfxVol=this._volume('sfxVolume');if(sfxVol<=0)return;this._initializeContext();if(!this._audioCtx)return;if(this._audioCtx.state==='suspended')this._audioCtx.resume();let soundDef=this._soundMap[key];if(!soundDef)return;this._sfxCount++;this.updateVolumes();const onEnd=()=>{this._sfxCount--;if(this._sfxCount<=0){this._sfxCount=0;this.updateVolumes();}};if(typeof soundDef==='string'){let buffer=this._buffers.get(key);if(!buffer){await this.loadSound(key,soundDef);buffer=this._buffers.get(key);}if(buffer){const source=this._audioCtx.createBufferSource(),gainNode=this._audioCtx.createGain();source.buffer=buffer;gainNode.gain.value=(options.volume!==undefined?options.volume:.5)*sfxVol;if(options.pitch)source.playbackRate.value=options.pitch;source.connect(gainNode);gainNode.connect(this._audioCtx.destination);source.onended=onEnd;source.start(0);}else onEnd();return;}if(!Array.isArray(soundDef))soundDef=[soundDef];const now=this._audioCtx.currentTime;let maxDuration=0;soundDef.forEach(note=>{try{const oscillator=this._audioCtx.createOscillator(),gainNode=this._audioCtx.createGain();oscillator.type=note.type||'square';let freq=note.frequency||440;if(options.pitch)freq*=options.pitch;oscillator.frequency.value=freq;const noteVol=note.volume||.3;gainNode.gain.value=(options.volume!==undefined?options.volume:.5)*noteVol*sfxVol;oscillator.connect(gainNode);gainNode.connect(this._audioCtx.destination);const startTime=now+(note.start||0)/1000,duration=(note.duration||100)/1000,endTime=(note.start||0)+(note.duration||100);if(endTime>maxDuration)maxDuration=endTime;oscillator.start(startTime);oscillator.stop(startTime+duration);}catch(e){console.error("SoundService note error:",e);}});setTimeout(onEnd,maxDuration);}
  static beep(frequency=440,duration=120){const sfxVol=this._volume('sfxVolume');if(sfxVol<=0)return;this._initializeContext();if(!this._audioCtx)return;if(this._audioCtx.state==='suspended')this._audioCtx.resume();this._sfxCount++;this.updateVolumes();const onEnd=()=>{this._sfxCount--;if(this._sfxCount<=0){this._sfxCount=0;this.updateVolumes();}};try{const oscillator=this._audioCtx.createOscillator(),gainNode=this._audioCtx.createGain();oscillator.type="square";oscillator.frequency.value=frequency;gainNode.gain.value=.2*sfxVol;oscillator.connect(gainNode);gainNode.connect(this._audioCtx.destination);oscillator.start();oscillator.stop(this._audioCtx.currentTime+duration/1000);oscillator.onended=onEnd;}catch(_e){onEnd();}}
}
