import { MidiParser, MidiPlayer } from "./midi.js";

const DEFAULT_SETTINGS = Object.freeze({ masterVolume: 0.5, musicVolume: 0.5, sfxVolume: 0.5 });

/** Browser audio infrastructure consumed through AudioAdapter. */
export class SoundService {
  static _audioCtx = null; static _buffers = new Map(); static _soundMap = {}; static _midiData = new Map(); static _musicPlayer = null; static _sfxCount = 0; static _currentMusicKey = null; static _settings = DEFAULT_SETTINGS;
  static configureSettings(settings) { if (!settings) throw new TypeError("SoundService requires a settings provider."); this._settings=settings; this.updateVolumes(); }
  static _volume(kind) { return Number(this._settings.masterVolume ?? .5) * Number(this._settings[kind] ?? .5); }
  static async init(soundMap) { this._soundMap=soundMap||{}; this._initializeContext(); return this.loadAll(); }
  static _initializeContext() { if(!this._audioCtx && typeof window!=="undefined" && (window.AudioContext||window.webkitAudioContext)) this._audioCtx=new (window.AudioContext||window.webkitAudioContext)(); if(this._audioCtx&&!this._musicPlayer)this._musicPlayer=new MidiPlayer(this._audioCtx); }
  static async loadAll() { if(!this._audioCtx)return; const promises=Object.entries(this._soundMap).map(([k,v])=>typeof v==='string'?this.loadSound(k,v):Promise.resolve()); const folder='assets/midi/'; let files=['battle1.mid','dungeon1.mid','town1.mid','event1.mid','event2.mid','victory1.mid','coverCapsuleHello.mid','emotional1_bitSad.mid','emotional2_sadNostalgic.mid','emotional3_sadSad.mid','event3.mid','event4_darkJester.mid','event5_nostalgia.mid','event6_happyfinality.mid','event7_happyPrelude.mid','event8_yearning.mid','event9_magical.mid']; try{const response=await fetch(folder);if(response.ok){const text=await response.text();const found=[];for(const match of text.matchAll(/href="([^"]+\.mid)"/g)){const name=decodeURI(match[1]).split('/').pop();if(name&&!found.includes(name))found.push(name);}if(found.length)files=found;}}catch(e){console.warn('Dynamic MIDI scan failed, using fallback list.',e);} files.forEach(file=>promises.push(this.loadMidi(file.replace(/\.mid$/i,''),folder+file))); await Promise.allSettled(promises); }
  static async loadSound(key,path){if(!this._audioCtx)return;try{const response=await fetch(path);if(!response.ok)throw new Error(`HTTP error ${response.status}`);this._buffers.set(key,await this._audioCtx.decodeAudioData(await response.arrayBuffer()));}catch(error){console.warn(`SoundService: Failed to load sound '${key}' from '${path}'.`,error);}}
  static async loadMidi(key,path){if(!this._audioCtx)return;try{const response=await fetch(path);if(!response.ok)throw new Error(`HTTP error ${response.status}`);this._midiData.set(key,new MidiParser(await response.arrayBuffer()).parse());}catch(error){console.warn(`SoundService: Failed to load midi '${key}' from '${path}'.`,error);}}
  static playMusic(key){this._initializeContext();if(!this._audioCtx)return;if(this._audioCtx.state==='suspended')this._audioCtx.resume();if(this._currentMusicKey===key&&this._musicPlayer.isPlaying){this.updateVolumes();return;}const data=this._midiData.get(key);if(!data){console.warn(`SoundService: Music '${key}' not found or not loaded.`);this.stopMusic();return;}this._currentMusicKey=key;this._musicPlayer.load(data);this._musicPlayer.play(true);this.updateVolumes();}
  static stopMusic(){if(this._musicPlayer)this._musicPlayer.stop();this._currentMusicKey=null;} static pauseMusic(){this._musicPlayer?.pause();} static resumeMusic(){this._musicPlayer?.resume();} static isMusicPlaying(){return !!this._musicPlayer?.isPlaying;} static getMusicDuration(){return this._musicPlayer?.duration||0;} static getMusicTime(){return this._musicPlayer?.currentTime||0;} static getCurrentMusicKey(){return this._currentMusicKey;} static getMusicKeys(){return Array.from(this._midiData.keys()).sort();} static getSfxKeys(){return Object.keys(this._soundMap).sort();}
  static updateVolumes(){if(!this._audioCtx)return;const volume=this._sfxCount>0?0:this._volume('musicVolume')*.6;this._musicPlayer?.setVolume(volume);}
  static async play(key,options={}){const sfxVol=this._volume('sfxVolume');if(sfxVol<=0)return;this._initializeContext();if(!this._audioCtx)return;if(this._audioCtx.state==='suspended')this._audioCtx.resume();let def=this._soundMap[key];if(!def)return;this._sfxCount++;this.updateVolumes();const onEnd=()=>{this._sfxCount=Math.max(0,this._sfxCount-1);this.updateVolumes();};if(typeof def==='string'){let buffer=this._buffers.get(key);if(!buffer){await this.loadSound(key,def);buffer=this._buffers.get(key);}if(!buffer){onEnd();return;}const source=this._audioCtx.createBufferSource(),gain=this._audioCtx.createGain();source.buffer=buffer;gain.gain.value=(options.volume??.5)*sfxVol;if(options.pitch)source.playbackRate.value=options.pitch;source.connect(gain);gain.connect(this._audioCtx.destination);source.onended=onEnd;source.start(0);return;}if(!Array.isArray(def))def=[def];const now=this._audioCtx.currentTime;let max=0;for(const note of def){try{const osc=this._audioCtx.createOscillator(),gain=this._audioCtx.createGain();osc.type=note.type||'square';osc.frequency.value=(note.frequency||440)*(options.pitch||1);gain.gain.value=(options.volume??.5)*(note.volume||.3)*sfxVol;osc.connect(gain);gain.connect(this._audioCtx.destination);const start=now+(note.start||0)/1000,duration=(note.duration||100)/1000;max=Math.max(max,(note.start||0)+(note.duration||100));osc.start(start);osc.stop(start+duration);}catch(e){console.error('SoundService note error:',e);}}setTimeout(onEnd,max);}
  static beep(frequency=440,duration=120){const sfxVol=this._volume('sfxVolume');if(sfxVol<=0)return;this._initializeContext();if(!this._audioCtx)return;if(this._audioCtx.state==='suspended')this._audioCtx.resume();this._sfxCount++;this.updateVolumes();const onEnd=()=>{this._sfxCount=Math.max(0,this._sfxCount-1);this.updateVolumes();};try{const osc=this._audioCtx.createOscillator(),gain=this._audioCtx.createGain();osc.type='square';osc.frequency.value=frequency;gain.gain.value=.2*sfxVol;osc.connect(gain);gain.connect(this._audioCtx.destination);osc.start();osc.stop(this._audioCtx.currentTime+duration/1000);osc.onended=onEnd;}catch(_e){onEnd();}}
}
